displayName=Dynamic Treads
author=blakos
description=Transmog Avernic Treads based on attack style
tags=transmog,cosmetic,boots,avernic,primordial,pegasian,eternal
plugins=com.dynamictreads.DynamicTreadsPlugin
build=standard
